package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import dao.mappers.IMapResultSetIntoEntity;
import dao.repositories.IUserRepository;
import domain.model.User;
import dao.uow.IUnitOfWork;

public class UserRepository extends RepositoryBase<User> implements IUserRepository {

	public UserRepository(Connection connection, IMapResultSetIntoEntity<User> mapper, IUnitOfWork uow) {
		super(connection, mapper, uow);
	}

	private PreparedStatement getUsername;
	private PreparedStatement getSurname;

	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE user(" + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "username varchar(50)," + "surname varchar(50)" + ")";
	}

	@Override
	protected String tableName() {
		return "user";
	}

	protected String insertSql() {
		return "INSERT INTO user (username, surname) VALUES (?,?)";
	}

	protected String updateSql() {
		return "UPDATE user SET (username, surname)=(?,?) WHERE id=?";
	}

	protected String getNameSql() {
		return "SELECT * FROM user where username = ?";
	}

	protected String getSurNameSql() {
		return "SELECT * FROM user where surName=?";
	}

	@Override
	protected void setUpdate(User user) throws SQLException {
		update.setString(1, user.getUsername());
		update.setString(2, user.getSurname());

	}

	@Override
	protected void setInsert(User user) throws SQLException {
		insert.setString(1, user.getUsername());
		insert.setString(2, user.getSurname());
	}

	private List<User> searchBy(String value) {
		List<User> user = new ArrayList<>();
		try {
			getUsername.setString(1, value);
			ResultSet resultSet = getUsername.executeQuery();
			while (resultSet.next()) {
				user.add(mapper.map(resultSet));
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return user;
	}

	public List<User> withUsername(String username) {
		return searchBy(username);
	}

	public List<User> withSurname(String surname) {
		return searchBy(surname);
	}

}
